[Config]
Dependencies=
	image

[Output]
Format=disk
ManifestFormat=json
SplitArtifacts=true

[Content]
BaseTrees=%O/%i.tar
KernelCommandLine=rw

# Security utilities
InitrdPackages=
	tpm2-tss
	libp11-kit
	libfido2

# Filesystem utilities
InitrdPackages=
	lvm2
	e2fsprogs
	exfatprogs
	btrfs-progs
