[Distribution]
Distribution=arch

[Output]
ImageId=NekkOS
Output=%i
BuildDirectory=mkosi.builddir
CacheDirectory=mkosi.cache
OutputDirectory=mkosi.output/%v

[Validation]
Checksum=true
SignExpectedPcr=true
SecureBoot=true
SecureBootAutoEnroll=true

[Host]
Ephemeral=true
Incremental=true
ToolsTree=default
