[Output]
Format=tar
CompressOutput=false

[Content]
Bootable=false
CleanPackageMetadata=false

# Kernel & Firmware
Packages=
	linux
	linux-firmware

# CPU Microcode
Packages=
	amd-ucode
	intel-ucode

# systemd utilities
Packages=
	systemd
	qrencode
	libpwquality

# Security utilities
Packages=
	tpm2-tss
	libp11-kit
	libfido2

# Filesystem utilities
Packages=
	lvm2
	e2fsprogs
	exfatprogs
	btrfs-progs

# Userspace utilities
Packages=
	glibc
	glibc-locales
	bash
	bash-completion
	mandoc
	man-pages
	posix
	nano

# Archive formats
Packages=
	libarchive
	p7zip
	unzip
	zip

# Compession formats
Packages=
	bzip2
	bzip3
	gzip
	lrzip
	lz4
	lzip
	lzop
	xz
	zstd

# Bluetooth
Packages=
	bluez
	bluez-cups
	bluez-tools

# Wireless
Packages=
	broadcom-wl
	iptables-nft

# Networking
Packages=
	networkmanager
	networkmanager-openconnect
	networkmanager-openvpn
	modemmanager

# Development files
RemoveFiles=
	/usr/lib/*.a
	/usr/lib/*.o
	/usr/lib/*/include/
	/usr/include/
	/usr/src/
	/usr/local/

# Packaging files
RemoveFiles=
	/usr/lib/cmake/
	/usr/lib/pkgconfig/
	/usr/share/cmake/
	/usr/share/pkgconfig/
